### ISSUE TITLE
Import lodash func by path instead of destructuring

### ISSUE THREAD

**Issue by foray1010** [steelsojka/lodash-decorators#22]
currently, lodash-decorators import lodash by `import { bind } from 'lodash';`
I suggest to import by `import bind from 'lodash/bind';` instead
the reason is the current implementation will import the whole 685kb lodash, it is large for frontend application

**Comment by steelsojka** [comment]
Thanks for noticing ;). This was on my road map (if it was documented). I'll do this sometime this week.

**Comment by steelsojka** [comment]
Closed in 4efdd7c0238aa721bcd9289f65534bde12e0538e w/ release 2.4.1
