### ISSUE TITLE
[SourceMaps] Missing source files in the npm package

### ISSUE THREAD

**Issue by JabX** [steelsojka/lodash-decorators#25]
Version : 4.3.3

The source files (the entire `src` folder) are missing in the package downloaded from npm, meaning that source maps cannot be used and that I'm getting a ton of warnings with `webpack` and `source-map-loader` about these missing files.

**Comment by steelsojka** [comment]
The `src` folder is not included intentionally. The source maps are located at the root level in adjacent to the `.js` file. `source-map-loader` configuration issue?

For example `after.js` and `after.js.map` are in the root directory. The source mapping URL looks like this in `after.js` -> `//# sourceMappingURL=after.js.map`

What is the webpack error?

**Comment by steelsojka** [comment]
Sorry, I just realized that the source map points to the source file. My bad. I should have though about it before replying. I'll remove the src folder from the .npmignore file in the next version.

**Comment by steelsojka** [comment]
Fixed 5f2d8750de49996a817969f9fdad6df81fc4af09. Released in v4.3.4. Let me know if this is still an issue.
