### ISSUE TITLE
bindAll: Class constructor cannot be invoked without 'new'

### ISSUE THREAD

**Issue by ghost** [steelsojka/lodash-decorators#26]
I'm getting the error `Class constructor Foo cannot be invoked without 'new'` when using `@bindAll()` on a class, with the following line highlighted:

https://github.com/steelsojka/lodash-decorators/blob/a30b1960e76cb169235ce59d261348edde7a5b39/src/bindAll.ts#L34

**Comment by steelsojka** [comment]
@errorx666 Can you please give me a code sample that reproduces the issue? Also, are you using a transpiler of any kind?

**Comment by ghost** [comment]
Webpack babel-loader.

(You need a transpiler for decorators for all current implementations, right?)

**Comment by steelsojka** [comment]
@errorx666 Do you have a code example? I've used this library with webpack and the babel loader and have not had any problems.

EDIT:

I added a unit test for this and it is passing. I'll need some more info about your project.

https://github.com/steelsojka/lodash-decorators/blob/master/src/bindAll.spec.ts#L113

**Comment by steelsojka** [comment]
@errorx666 I'm gonna close this as not reproducible. If you continue to see this and can provide a code sample we can reopen it.

**Comment by icfantv** [comment]
@steelsojka I'm getting this error in our project when executing our Jest tests.  I will attempt at creating an example and create a new issue if reproducible.
