### ISSUE TITLE
Mixin doesn't mixes in symbol properties

### ISSUE THREAD

**Issue by laggingreflex** [steelsojka/lodash-decorators#28]
```js
const private = Symbol('private')
const myMixin = {
  [private]: () => {...}
  publicMethod () => {
    this[private] // undefined
  }  
}
@mixin(myMixin)
class {
  ...
}
```

I wanted to use this as a substitute for private fields.

I'm guessing it only mixes in plain text properties. 

Would it be possible to allow mixing in symbol properties? I'm not even sure if it'd be a good idea to mixin all properties as such, I haven't really used mixins before this, and even now I only wanted to use it because of this very use case.

**Comment by steelsojka** [comment]
@laggingreflex This just does an `_.assign` behind the scenes so it will only mixin own enumerable properties. I'm hesitant to allow mixing in of Symbols by default as it would be a breaking change. A mixin should mixin all enumerable properties of the object being mixed in (the point of a mixin).

**Comment by laggingreflex** [comment]
Thanks for clarification, makes sense.
