### ISSUE TITLE
Function Expressions

### ISSUE THREAD

**Issue by Sicria** [steelsojka/lodash-decorators#42]
Can't seem to use ``@Debounce`` on function expressions.

```
class Person {
  @Debounce(300)
  handleSearch = () => {
    console.log('called function');
  };
}
```

Am I using the package wrong?

**Comment by steelsojka** [comment]
Debounce can only work on methods of a class and not function expressions. The decorator does not and can not (at this time) inspect values assigned to a property. So this would work by doing:

```javascript
class Person {
  @Debounce(300)
  handleSearch() {
    console.log('called function');
  }
}
```
