### ISSUE TITLE
Use `@bind()` without parenthesis

### ISSUE THREAD

**Issue by misantronic** [steelsojka/lodash-decorators#43]
When using `@bind()` the parenthesis are required. It would be really nice if this was optional since there is no need for a parameter.

**Comment by steelsojka** [comment]
This is by design. Mostly to easily add options to or any number of parameters without breaking existing behavior. I'll look into making it optional. Might be a little tricky with the typescript typings.

**Comment by Prior99** [comment]
I'd also be happy if it were possible to call all decorators by `@bind` instead of `@bind()`. This makes it visually more consistent to Mobx and other libraries.

**Comment by steelsojka** [comment]
@Prior99 I think this depends on the library. If you look at Angular all the decorators require invocation, even the ones that take no parameters. It's a design decision that I'm more in favor of. I'm still on the fence about having them optional...

**Comment by steelsojka** [comment]
This looks trivial. I'll try to get to it in the next few days.

**Comment by Prior99** [comment]
Thanks, this allows me to replace libraries like `bind-decorator` with this marvelous library. Thanks for the great work.

**Comment by steelsojka** [comment]
Added in 6f123b7b7eeb1a98f1e0f1ffc2c9e8ea75f872a9. Let me know if you see any issues!
