### ISSUE TITLE
Different sizes for different import-styles

### ISSUE THREAD

**Issue by misantronic** [steelsojka/lodash-decorators#44]
So, I tried using lodash-decorators with the most common import-syntax (and my favorite)

```js
import { bind, debounce } from 'lodash-decorators';
```

When using lodash-decorators in my project this way I get this filesize:

![screen shot 2018-02-27 at 14 22 18](https://user-images.githubusercontent.com/6033531/36731069-d933ff88-1bc9-11e8-8239-6ab919c9468f.png)

Which seems weirdly big.
So I tried the other import-syntax

```js
import bind from 'lodash-decorators/bind';
import debounce from 'lodash-decorators/debounce';
```

Which results in a different size

<img width="294" alt="screen shot 2018-02-27 at 14 21 08" src="https://user-images.githubusercontent.com/6033531/36731120-0309cbf8-1bca-11e8-886c-6da744c0174d.png">

My question is, why they differ at all and why is the overall size of imported source so big for just 2 lodash-functions.

**Comment by steelsojka** [comment]
When you import by named imports it includes the entire library unless you're bundler is tree shaking. You're importing from the main export file which exports everything. When you import by a more specific path you are only including that file and anything that it imports. You aren't getting the entire library.

**Comment by Feofilakt** [comment]
Still too big for 2 functions. Very suspicious.

**Comment by steelsojka** [comment]
@Feofilakt I don't understand your comment. Can you please clarify?

**Comment by steelsojka** [comment]
It's not merely "just 2 functions" There's a lot under the hood making those functions work. Take a look at the source and the utilities that used to apply the decorators (and compose them correctly).

**Comment by Feofilakt** [comment]
I was mostly saying about "lodash 123 kB..." in second TS screen. If each lodash function is in separate file, then importing 2 functions should use 2 files? Or not?

**Comment by steelsojka** [comment]
Lodash internally includes lots of files for just a single function. Take a look at the lodash source code. Also, the build that this lib depends on does not use ES modules, so it can't be optimized like lodash-es. That's most likely why you see a much higher file size.
