### ISSUE TITLE
Combine decorators?

### ISSUE THREAD

**Issue by waynebrantley** [steelsojka/lodash-decorators#51]
I would like to make a 'DebounceAndBind' decorator - that does both the debounce and the bind.
Currently, we use all lambda functions - and do not have to bind anywhere - but anything debounced cannot be a lambda - so it has to use bind.  So anytime we end up with @debounce, we also must add @bind.   

Thought it would be nice if I could combine into one - but do not really see how to do that.  I can easily wrap one of the decorators with another decorator - but do not see how to do this?

**Comment by steelsojka** [comment]
@waynebrantley Can you give me a code example on what you are doing?

**Comment by waynebrantley** [comment]
```
import { debounce, LodashDecorator } from "lodash-decorators"
import { bind } from "lodash-decorators"

const debounceThreshold: number = 1000
export function debounceButton(): LodashDecorator {
    return debounce(debounceThreshold, { leading: true, trailing: false })
}

//how to make a 
export function debounceAndBindButton(): LodashDecorator {
    //how to do the bind decorator here?
    return debounce(debounceThreshold, { leading: true, trailing: false })
}

```

**Comment by waynebrantley** [comment]
So, in that ``debounceAndBindButton`` - was trying to figure out how to also do binding?

**Comment by waynebrantley** [comment]
@steelsojka Any ideas?  Of course, we can always just put both everywhere

**Comment by steelsojka** [comment]
@waynebrantley The cleanest way is to just use both decorators since decorators are already composable.  If you really want to you can recreate this behavior behind another decorator.

```typescript
import { Bind, Debounce } from 'lodash-deocrators';

export function DebounceAndBind(debounceTime: number): MethodDecorator {
  const debounce = Debounce(debounceTime, { leading: true, trailing: true });
  const bind = Bind();

  return (target, key, descriptor) => debounce(target, key, (bind(target, key, descriptor) || descriptor));
}
```

Just note that this may not work with the current and future specification. So there will be a future version of this library that won't support this spec (at least not without some sort of mapper to the old format)

**Comment by waynebrantley** [comment]
You said there 'will be' a future version that will not support this?  Or might be?
Seems like the decorators should be composable into combined decorators too (as a supported thing).

Anyway, what you posted already does not work today (according to typescript).
Using ``const bind = Bind() as any;`` forces it to compile - and then it does seem to work..

>>[ts]
Argument of type 'void | TypedPropertyDescriptor<T>' is not assignable to parameter of type 'TypedPropertyDescriptor<T>'.
  Type 'void' is not assignable to type 'TypedPropertyDescriptor<T>'.
const bind: <T>(target: Object, propertyKey: string | symbol, descriptor: TypedPropertyDescriptor<T>) => void | TypedPropertyDescriptor<T>
<<

Thoughts - or should I abandon this?

**Comment by steelsojka** [comment]
This is because the decorator can be used with or without invocation so typescript doesn't know which one is being applied here. You can do `Bind() as LodashDecorator`
