### ISSUE TITLE
decorators lose `this` context in Vue class components

### ISSUE THREAD

**Issue by kiyui** [steelsojka/lodash-decorators#57]
Hey, thanks for this great project. I've been using it to replace my own implementation of `lodash` decorators in projects. I have run into an issue however.

It seems that attaching decorators to a Vue class component event handler method causes the method to lose its `this` context. Full demo [here](https://stackblitz.com/edit/class-component-lodash-decorator).
```typescript
import Vue from 'vue'
import Vuex from 'vuex'
import { Component } from 'vue-property-decorator'
import { Debounce } from 'lodash-decorators'

@Component
export default class ItemAdder extends Vue {
  private value: string = 'unknown'

  public addItem () {
    this.$store.commit('ADD_ITEM', { item: this.value })
  }

  @Debounce(500)
  public onInput (e) {
    // this === window
    this.value = e.target.value
  }

  public render (h: Vue.CreateElement) {
    return h('div', {}, [
      h('p', {}, [`My value is ${this.value}`]),
      h('input', { attrs: { type: 'text'}, on: { input: this.onInput } }),
      h('button', { on: { click: this.addItem } }, ['Submit'])
    ])
  }
}
```
There is a simple fix for this of course, by doing:
```diff
        h('p', {}, [`My value is ${this.value}`]),
--      h('input', { attrs: { type: 'text'}, on: { input: this.onInput } }),
++      h('input', { attrs: { type: 'text'}, on: { input: this.onInput.bind(this) } }),
```
However, this is not an option for when we are not using a `render` function, such as using `.vue` files to compile templates.
```vue
<template>
  <!-- etc -->
</template>
<script lang="ts">
// etc
</script>
```

This also means that `lodash-decorators` cannot be a drop-in replacement for existing code. Here's an implementation of `Debounce` that does in fact work with Vue class components:
```typescript
import debounce from 'lodash/debounce'

export function Debounce (duration: number) {
  return (target: Object, propertyKey: string, descriptor: TypedPropertyDescriptor<any>) => {
    const targetFn = descriptor.value
    if (typeof targetFn === 'function') {
      descriptor.value = debounce.apply(target, [ targetFn, duration ])
    }
  }
}
```
I hope this helps and can be addressed. Thanks again!

**Comment by steelsojka** [comment]
You can fix this one of two ways. You can bind the function as a property in the constructor.

```typescript
export class MyComponent {
  constructor() {
     this.onInput = this.onInput.bind(this);
  }

  @Debounce(500)
  onInput(): void {
    // this === MyComponent
  }
}
```
or you can use the `Bind` decorator provided by this package.

```typescript
  @Debounce(500)
  @Bind()
  public onInput (e) {
    this.value = e.target.value
  }
```

The problem we run into with the solution you have posted above is now our `onInput` function shares the same debounce timer across all component instances, which is not what you want. It also calls in the context of the prototype and not the class instance so you would end up assigning you input variable to the prototype which would also overwrite across component instances.

Either of the above should work. Binding the context is a side effect that I don't think debounce should perform as the user may have the intent of calling the function in another context.

I appreciate you taking the time to write this out. Thanks for the feedback and I hope this helps!

**Comment by kiyui** [comment]
Thanks, I suppose you're right! I suppose my mistake was trying:
```typescript
@BindAll()
@Component()
```
Instead of a single `@Bind()` per method!
