### ISSUE TITLE
@Throttle

### ISSUE THREAD

**Issue by AnkhHeart** [steelsojka/lodash-decorators#59]
The @Throttle decorator has no idea what 'this' is anymore inside of the function. Any variables or functions calls on 'this' come back as undefined / ucallable.

**Comment by steelsojka** [comment]
@AnkhHeart Can you provide an example of how you are calling the throttled function? The function is invoked within the calling context, so it's most likely you are calling the function with no caller. Keep in mind the throttle function does not bind to the this context of the class for you.

**Comment by AnkhHeart** [comment]
It's being used as any other decorator would be:
```
class ClassNameHere {

 @Throttle(1000)
  executeCode(){
    if(this.type == 'test'){
    	// Exec A
    } else {
    	// Exec B
    }
  }
}
```

**Comment by steelsojka** [comment]
@AnkhHeart  What I mean is how are you calling "executeCode"? It will the same rules as if you didn't have the decorator.

```typescript
const instance = new ClassNameHere();

instance.executeCode(); // this will be "instance"

const fn = instance.executeCode;

fn(); // This will be window or global
```
Can you give me an example of how you are calling the function?

**Comment by steelsojka** [comment]
Closing for now. If there are more problems let me know.
