### ISSUE TITLE
mocha:unit.js File name causes issues on windows

### ISSUE THREAD

**Issue by Bretto** [steelsojka/lodash-decorators#8]
when downloading the zip of the project it creates a folder form mocha and breaks gulp.

**Comment by steelsojka** [comment]
Does it report which folder? Is this while unzipping or during `npm install`?

**Comment by Bretto** [comment]
yes, mocha:unit.js and tdd:unit.js in gulp task are the one causing the issue, I don't remember it it was before or after the npm install but renaming it with an "_" instead of the ":" fix the issue.

**Comment by steelsojka** [comment]
Looks like windows doesn't allow colons in file names. I'll rename them with valid characters for windows.

**Comment by steelsojka** [comment]
Fixed with 99d977ecba4640d431dc1c292e3f458c41c7b8e2
