### ISSUE TITLE
Can't get it to work with module loader

### ISSUE THREAD

**Issue by Bretto** [steelsojka/lodash-decorators#9]
I am using JSPM

```
"jspm": {
    "directories": {
      "baseURL": "client"
    },
    "dependencies": {
      "angular": "github:angular/bower-angular@1.4.1",
      "jquery": "github:components/jquery@^2.1.4",
      "lodash": "github:lodash/lodash@3.10.0",
      "lodash-decorators": "npm:lodash-decorators@^0.4.10"
    },
    "devDependencies": {
      "babel": "npm:babel-core@^5.1.13",
      "babel-runtime": "npm:babel-runtime@^5.1.13",
      "core-js": "npm:core-js@^0.9.4"
    }
  }
```

simple use-case

```
class LoginController {

    constructor() {
    }

    @bind()
    isUsernameAvailable() {
      console.log(this);
    }
}
```

Error

```
Internal Error  TypeError: Error evaluating src/app/AppModule
Error evaluating src/forms/LoginController
bind is not a function
```

Is lodash-decorators compatible with a module loader ? I can't get it to work...

**Comment by steelsojka** [comment]
It will work with any CommonJS loader (NodeJs, browserify). I haven't used JSPM before so I'm not sure what needs to happen to make it work with it. I will research it a bit.

Are you importing the module into the file? 

ES6:
`import { bind } from 'lodash-decorators';`

ES5:
`var bind = require('lodash-decorators).bind;`

**Comment by Bretto** [comment]
Here is the setup (ES6/7)

index.html

```
<script type="text/javascript" src="jspm_packages/system.js"></script>
<script type="text/javascript" src="config.js"></script>

<script>
    System.import('./src/bootstrap').catch(function (ex) {
        console.error('Internal Error ', ex && ex.stack || ex)
    });
</script>
```

config.js (add options)

```
"babelOptions": {
        "optional": [
            "es7.decorators",
            "es7.classProperties",
            "runtime"
        ]
    },
```

logingController.js

```
import { bind } from 'lodash-decorators';
import _ from 'lodash';
```

I am using 'ES6' modules this could be the issue...

**Comment by Bretto** [comment]
Any progress on your side off things ? (I am looking forward to integrate your project in our dev-env...)

**Comment by steelsojka** [comment]
I haven't had a time of time to dig into this yet. Are you transpiling? Are you using something like browserify to bundle up everything?

**Comment by Bretto** [comment]
I am transpiling at runtime, no build step for now...

**Comment by steelsojka** [comment]
I'm going to close this. The library is independent of the bundler. If this is still an issue and there is more information let me know.
